{% set name = "opentelemetry-exporter-prometheus" %}
{% set version = "0.46b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_prometheus-{{ version }}.tar.gz
  sha256: 28cc6456a5d5bf49c34be2f1d22bbc761c36af9b32d909ea5b4c13fe6deac47b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - opentelemetry-api >=1.24.0,<2.0
    - opentelemetry-sdk >=1.24.0,<2.0
    - prometheus_client >=0.5.0,<1.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.prometheus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-prometheus
  summary: Prometheus Metric Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - rxm7706
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-sdk
