{% set name = "opentelemetry-exporter-prometheus" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_prometheus-{{ version }}.tar.gz
  sha256: 50cede1d66d0f051946233e78b72b949bf59fea3f35260b0bdf6243a0cae28dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - opentelemetry-api >=1.12,<2.0
    - opentelemetry-sdk >=1.21,<2.0
    - prometheus_client >=0.5.0,<1.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.prometheus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-prometheus
  summary: Prometheus Metric Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
